// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IZOlro-f6BkEkKbnTKZQiGT8Q_2u7FY',
    appId: '1:953931101491:web:0e596c7c4ecfc9f87afa46',
    messagingSenderId: '953931101491',
    projectId: 'kubrayolcu-rezervedu',
    authDomain: 'kubrayolcu-rezervedu.firebaseapp.com',
    storageBucket: 'kubrayolcu-rezervedu.firebasestorage.app',
    measurementId: 'G-YV22VFEF8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO_rpMngUrBHP-IwUTEhUF4YnuphFAL2w',
    appId: '1:953931101491:android:9b93fd5132ca52477afa46',
    messagingSenderId: '953931101491',
    projectId: 'kubrayolcu-rezervedu',
    storageBucket: 'kubrayolcu-rezervedu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSh9d_7dOskjTfsxKob-QvAjKOp1VjwLQ',
    appId: '1:953931101491:ios:57964f1f2a56e1f77afa46',
    messagingSenderId: '953931101491',
    projectId: 'kubrayolcu-rezervedu',
    storageBucket: 'kubrayolcu-rezervedu.firebasestorage.app',
    iosBundleId: 'com.example.mobilAppEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSh9d_7dOskjTfsxKob-QvAjKOp1VjwLQ',
    appId: '1:953931101491:ios:57964f1f2a56e1f77afa46',
    messagingSenderId: '953931101491',
    projectId: 'kubrayolcu-rezervedu',
    storageBucket: 'kubrayolcu-rezervedu.firebasestorage.app',
    iosBundleId: 'com.example.mobilAppEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_IZOlro-f6BkEkKbnTKZQiGT8Q_2u7FY',
    appId: '1:953931101491:web:a5c5df40ec20e76e7afa46',
    messagingSenderId: '953931101491',
    projectId: 'kubrayolcu-rezervedu',
    authDomain: 'kubrayolcu-rezervedu.firebaseapp.com',
    storageBucket: 'kubrayolcu-rezervedu.firebasestorage.app',
    measurementId: 'G-ZGZ5GZTPYP',
  );
}
